### ISSUE TITLE
java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer on JDK 1.8

### ISSUE THREAD

**Issue by sayseakleng** [sotina/j8583#1]
Hello there! I just realized that a function doesn't work on JDK 1.8 but it works on the successors.

Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at com.solab.iso8583.IsoMessage.writeToBuffer(IsoMessage.java:377)

Testing environment:
j8583 version: 1.16.0
JDK: 1.8

I really appreciate for your contribution to this library.
Looks forward to getting the fix.

Best Regard,

Reno
